/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package uji_kelayakan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Muhamad Miftah
 */
public class laporan_periode extends javax.swing.JFrame {
    String sql;
    PreparedStatement prst;
    Connection con= new Login.koneksi().getConnection();
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    /** Creates new form laporan_periode */
    public laporan_periode() {
        initComponents();
    }
    
    public menu_utama menu;
    public input_tamu it;
    public laporan lp;
    public tamu_keluar tk;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cetak = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tanggal1 = new org.freixas.jcalendar.JCalendarCombo();
        tanggal2 = new org.freixas.jcalendar.JCalendarCombo();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        input_tamu = new javax.swing.JButton();
        laporan = new javax.swing.JButton();
        tamu_keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cetak.setBackground(new java.awt.Color(0, 153, 255));
        cetak.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cetak.setForeground(new java.awt.Color(255, 255, 255));
        cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Print_30px_1.png"))); // NOI18N
        cetak.setText("Cetak");
        cetak.setBorder(null);
        cetak.setBorderPainted(false);
        cetak.setContentAreaFilled(false);
        cetak.setOpaque(true);
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });
        jPanel1.add(cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 110, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("Lihat Laporan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Sampai Tanggal :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Dari Tanggal :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        tanggal1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tanggal1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(tanggal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 200, 40));

        tanggal2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tanggal2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(tanggal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 200, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 540, 430));

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("GuestBook");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Application");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 80));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Home_48px.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 100));

        input_tamu.setBackground(new java.awt.Color(0, 153, 255));
        input_tamu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Team_48px.png"))); // NOI18N
        input_tamu.setBorder(null);
        input_tamu.setContentAreaFilled(false);
        input_tamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_tamuActionPerformed(evt);
            }
        });
        jPanel2.add(input_tamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 90, 100));

        laporan.setBackground(new java.awt.Color(0, 153, 255));
        laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Report_Card_48px_1.png"))); // NOI18N
        laporan.setBorder(null);
        laporan.setContentAreaFilled(false);
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });
        jPanel2.add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 90, 100));

        tamu_keluar.setBackground(new java.awt.Color(0, 153, 255));
        tamu_keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Exit_48px.png"))); // NOI18N
        tamu_keluar.setBorder(null);
        tamu_keluar.setContentAreaFilled(false);
        tamu_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamu_keluarActionPerformed(evt);
            }
        });
        jPanel2.add(tamu_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 90, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 90, 430));

        setSize(new java.awt.Dimension(642, 548));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        // TODO add your handling code here:
        String reportSource = null;
        String reportDest = null;
        
        try{
            reportSource = "D:\\Study\\Kelas XI\\JAVA\\Latihan\\Uji_Kelayakan\\src\\uji_kelayakan\\tamu_periode.jrxml";
            reportDest = "D:\\Study\\Kelas XI\\JAVA\\Latihan\\Uji_Kelayakan\\src\\uji_kelayakan\\tamu_periode.jasper";
            HashMap parameter = new HashMap();
            String tanggal_awal = sdf.format(tanggal1.getDate());
            String tanggal_akhir = sdf.format(tanggal2.getDate());
            parameter.put("tanggal1", tanggal_awal);
            parameter.put("tanggal2", tanggal_akhir);
            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, con);
            JasperViewer.viewReport(jasperPrint, false);
        }catch(Exception e){
         e.printStackTrace();
        }
    }//GEN-LAST:event_cetakActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        menu = new menu_utama();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void input_tamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_tamuActionPerformed
        // TODO add your handling code here:
        it = new input_tamu();
        it.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_input_tamuActionPerformed

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
        // TODO add your handling code here:
        lp = new laporan();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporanActionPerformed

    private void tamu_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamu_keluarActionPerformed
        // TODO add your handling code here:
        tk = new tamu_keluar();
        tk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tamu_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan_periode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan_periode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan_periode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan_periode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporan_periode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cetak;
    private javax.swing.JButton input_tamu;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton laporan;
    private javax.swing.JButton tamu_keluar;
    private org.freixas.jcalendar.JCalendarCombo tanggal1;
    private org.freixas.jcalendar.JCalendarCombo tanggal2;
    // End of variables declaration//GEN-END:variables

}
