/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uji_kelayakan;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author Muhamad Miftah
 */
public class tamu_keluar extends javax.swing.JFrame {
    Connection con = new Login.koneksi().getConnection();
    ResultSet rs;
    Statement st;
    PreparedStatement prst;
    String sql;
    
    public menu_utama menu;
    public input_tamu it;
    public laporan lp;
    public tamu_keluar tk;
    public DefaultTableModel table_input_tamu;
    /**
     * Creates new form tamu_keluar
     */
    public tamu_keluar() {
        initComponents();
        table();
        tampil_table();
        tampil_data_table();
        tanggal();
    }

    public void table(){
        for (int a = 0; a < table_tamu.getColumnCount(); a++) {
            Class <?> b = table_tamu.getColumnClass(a);
            table_tamu.setDefaultEditor(b, null);
        }
    }
    
    public void tampil_table(){
        Object[]tampil_table = {"Kode Tamu","Nama Tamu","Alamat","Keperluan","No. Hp","Tanggal Masuk"};
        table_input_tamu = new DefaultTableModel(null, tampil_table);
        table_tamu.setModel(table_input_tamu);
    }

    public void tampil_data_table(){
        try{
            st = con.createStatement();
            table_input_tamu.getDataVector().removeAllElements();
            table_input_tamu.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM data_tamu WHERE status = 'DATANG'");
            while(rs.next()){
                Object[]data={
                    rs.getString("kd_tamu"),
                    rs.getString("nama_tamu"),
                    rs.getString("alamat"),
                    rs.getString("keperluan"),
                    rs.getString("no_telp"),
                    rs.getString("tanggal"),
                };
                table_input_tamu.addRow(data);
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }
    
    public void tanggal(){
        Date ys = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        tanggal_keluar.setText(s.format(ys));
    }
    
    public void reset(){
        kd_tamu.setText("");
        nama_tamu.setText("");
        alamat.setText("");
        keperluan.setText("");
        no_telp.setText("");
        tanggal.setText("");
    }
    
    public void edit(){
        try {
            int bar = table_tamu.getSelectedRow();
            String a = table_tamu.getValueAt(bar, 0).toString();
            String b = table_tamu.getValueAt(bar, 1).toString();
            String c = table_tamu.getValueAt(bar, 2).toString();
            String d = table_tamu.getValueAt(bar, 3).toString();
            String e = table_tamu.getValueAt(bar, 4).toString();
            String f = table_tamu.getValueAt(bar, 5).toString();

            kd_tamu.setText(a);
            nama_tamu.setText(b);
            alamat.setText(c);
            keperluan.setText(d);
            no_telp.setText(e);
            tanggal.setText(f);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void hapus(){
        if (kd_tamu.getText().equals("") || nama_tamu.getText().equals("") || alamat.getText().equals("") || keperluan.getText().equals("") || no_telp.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pilih Tamu Yang Akan Keluar!");
        }else{
            try{
                st = con.createStatement();
                st.executeUpdate("UPDATE data_tamu SET status = 'KELUAR' WHERE kd_tamu = '"+ kd_tamu.getText()+ "'");
                st.executeUpdate("INSERT INTO tamu_keluar SET kd_tamu = '"+ kd_tamu.getText() +"', "
                        + "nama_tamu = '"+ nama_tamu.getText() +"', alamat = '"+ alamat.getText() +"', "
                        + "keperluan = '"+ keperluan.getText() +"', no_telp = '"+ no_telp.getText() +"',"
                        + "tanggal = '"+ tanggal.getText() +"', tanggal_keluar = '"+ tanggal_keluar.getText() +"'");
                JOptionPane.showMessageDialog(null, "Tamu Keluar!","Informasi", JOptionPane.INFORMATION_MESSAGE);
                tampil_data_table();
                reset();
            }catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        no_telp = new javax.swing.JTextField();
        kd_tamu = new javax.swing.JTextField();
        nama_tamu = new javax.swing.JTextField();
        keperluan = new javax.swing.JTextField();
        hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_tamu = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        tanggal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        tcari = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tanggal_keluar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        input_tamu = new javax.swing.JButton();
        laporan = new javax.swing.JButton();
        tamu_keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("GuestBook");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Application");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 80));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel2.setText("Nomor Telepon");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel3.setText("Keperluan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("*cari berd. nama tamu");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel5.setText("Nama Tamu");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel6.setText("Kode Tamu");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        no_telp.setEditable(false);
        no_telp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(no_telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 250, 30));

        kd_tamu.setEditable(false);
        kd_tamu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(kd_tamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 250, 30));

        nama_tamu.setEditable(false);
        nama_tamu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(nama_tamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 250, 30));

        keperluan.setEditable(false);
        keperluan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(keperluan, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 250, 30));

        hapus.setBackground(new java.awt.Color(0, 153, 255));
        hapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Denied_30px.png"))); // NOI18N
        hapus.setText("Keluar");
        hapus.setBorder(null);
        hapus.setBorderPainted(false);
        hapus.setContentAreaFilled(false);
        hapus.setOpaque(true);
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel1.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 130, 40));

        table_tamu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_tamu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_tamuMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table_tamu);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 790, 130));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel7.setText("Tanggal Keluar");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        tanggal.setEditable(false);
        tanggal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 250, 30));

        alamat.setEditable(false);
        alamat.setColumns(20);
        alamat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alamat.setRows(5);
        jScrollPane2.setViewportView(alamat);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 250, 70));

        tcari.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tcariKeyReleased(evt);
            }
        });
        jPanel1.add(tcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 260, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("Cari");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel11.setText("Alamat");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel12.setText("Tanggal Masuk");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        tanggal_keluar.setEditable(false);
        tanggal_keluar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(tanggal_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 250, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 860, 450));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Home_48px.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 100));

        input_tamu.setBackground(new java.awt.Color(0, 153, 255));
        input_tamu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Team_48px.png"))); // NOI18N
        input_tamu.setBorder(null);
        input_tamu.setContentAreaFilled(false);
        input_tamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_tamuActionPerformed(evt);
            }
        });
        jPanel2.add(input_tamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 90, 100));

        laporan.setBackground(new java.awt.Color(0, 153, 255));
        laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Report_Card_48px_1.png"))); // NOI18N
        laporan.setBorder(null);
        laporan.setContentAreaFilled(false);
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });
        jPanel2.add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 90, 100));

        tamu_keluar.setBackground(new java.awt.Color(0, 153, 255));
        tamu_keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Exit_48px.png"))); // NOI18N
        tamu_keluar.setBorder(null);
        tamu_keluar.setContentAreaFilled(false);
        tamu_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamu_keluarActionPerformed(evt);
            }
        });
        jPanel2.add(tamu_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 90, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 90, 450));

        setSize(new java.awt.Dimension(965, 563));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        hapus();
    }//GEN-LAST:event_hapusActionPerformed

    private void table_tamuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_tamuMousePressed
        // TODO add your handling code here:
        edit();
    }//GEN-LAST:event_table_tamuMousePressed

    private void tcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyReleased
        // TODO add your handling code here:
        try{
            st = con.createStatement();
            table_input_tamu.getDataVector().removeAllElements();
            table_input_tamu.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM data_tamu WHERE status = 'DATANG' AND nama_tamu LIKE '%"+ tcari.getText() +"%'");
            while(rs.next()){
                Object[]data={
                    rs.getString("kd_tamu"),
                    rs.getString("nama_tamu"),
                    rs.getString("alamat"),
                    rs.getString("keperluan"),
                    rs.getString("no_telp"),
                    rs.getString("tanggal"),
                };
                table_input_tamu.addRow(data);
            }
        }catch (Exception e) {
                e.printStackTrace();
        }
    }//GEN-LAST:event_tcariKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        menu = new menu_utama();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void input_tamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_tamuActionPerformed
        // TODO add your handling code here:
        it = new input_tamu();
        it.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_input_tamuActionPerformed

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
        // TODO add your handling code here:
        lp = new laporan();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_laporanActionPerformed

    private void tamu_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamu_keluarActionPerformed
        // TODO add your handling code here:
        tk = new tamu_keluar();
        tk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tamu_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tamu_keluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tamu_keluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tamu_keluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tamu_keluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tamu_keluar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton hapus;
    private javax.swing.JButton input_tamu;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kd_tamu;
    private javax.swing.JTextField keperluan;
    private javax.swing.JButton laporan;
    private javax.swing.JTextField nama_tamu;
    private javax.swing.JTextField no_telp;
    private javax.swing.JTable table_tamu;
    private javax.swing.JButton tamu_keluar;
    private javax.swing.JTextField tanggal;
    private javax.swing.JTextField tanggal_keluar;
    private javax.swing.JTextField tcari;
    // End of variables declaration//GEN-END:variables
}
